### ISSUE TITLE
okokChatV2 dont work

### ISSUE THREAD

**Issue by germandreym** [SirLamaGott/lama_admin-v3#1]
Hey We use okokChatV2 But the Script Dont give the Support Message

**Comment by SirLamaGott** [comment]
I will fix this today, thanks for the report 👍🏻

**Comment by germandreym** [comment]
Fixed?

**Comment by SirLamaGott** [comment]
should be fixed by now sorry.

**Comment by SirLamaGott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [okokChatV2 not working](https://trello.com/c/I6wc3gQJ/5-okokchatv2-not-working)
